### PR TITLE
feat(shorebird_cli): reintroduce releases list command

### LINKED ISSUE #1339: feat: Shorebird Release List
**Description**

I would like the ability to use the shorebird CLI to list all releases and also list the current release. I have my CI system Bitrise auto increment a release's build number using the CI build's number. I do not track this build number in my git. When I go to run the patch workflow, I need to know the current release so I can strip off the build number and set for the patch using the flutter build arg --build-number.

This allows me to sync the patches to the release.

**CLI Command Requirements**

- [ ] shorebird releases list (Lists all releases)
- [ ] shorebird releases current (Lists the current/top release)

**Additional Context**

Discussed in Discord https://discord.com/channels/1030243211995791380/1125516353370075306/1158075745864786032

### PR DESCRIPTION
**Pull request by bryanoltman**
## Description

Reintroduces the `shorebird releases list` command, back by popular demand.

Fixes https://github.com/shorebirdtech/shorebird/issues/1339

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
Is this needed? I think by allowing folks to specify a release version when patching we’ve solved the op’s issue without having to reintroduce a releases list command.

**Comment by bryanoltman** [comment]
@felangel based on the bug, I think being able to set the release version on the patch is only the second half of the issue:

> I need to know the current release so I can strip off the build number and set for the patch using the flutter build arg --build-number.

**Review by eseidel — APPROVED** [review]

**Comment by eseidel** [comment]
I do wonder if we're adding CLI here when what customers might want is API?

**Comment by felangel** [comment]
Based on the conversation in Discord, I suggest we close this and instead output the release version from the GitHub Action.

**Comment by bryanoltman** [comment]
SGTM

**Pull request closed without merging**
