### PR TITLE
chore: split versions_test from cutler_test, mostly to trigger coverage

### PR DESCRIPTION
**Pull request by eseidel**
split versions_test from cutler_test, mostly to trigger coverage

### CODE REVIEW

**Comment by eseidel** [comment]
@felangel maybe `secrets` is not valid in actions, only workflows?

**Comment by felangel** [comment]
> @felangel maybe `secrets` is not valid in actions, only workflows?

Ah yeah good call we’ll need to add it as an input to the action. I’ll make that change shortly 👍

**Comment by felangel** [comment]
Should be fixed by #619

**Comment by bryanoltman** [comment]
`14.035087719298245 is greater than or equal to min_coverage 10.` 🙌

**Review by bryanoltman — APPROVED** [review]

**Pull request merged**
