### PR TITLE
feat(shorebird_cli): improve `shorebird apps list` display

### PR DESCRIPTION
**Pull request by felangel**
## Description

- feat(shorebird_cli): improve `shorebird apps list` display

```
📱 Apps
┌───────────────────┬──────────────────────────────────────┬─────────┬───────┐
│ Name              │ ID                                   │ Release │ Patch │
├───────────────────┼──────────────────────────────────────┼─────────┼───────┤
│ Shorebird Counter │ 30370f27-dbf1-4673-8b20-fb096e38dffa │ 1.0.0   │ 1     │
├───────────────────┼──────────────────────────────────────┼─────────┼───────┤
│ Shorebird Clock   │ 05b45471-a5f3-48cd-b26a-da29d95914a7 │ --      │ --    │
└───────────────────┴──────────────────────────────────────┴─────────┴───────┘
```

## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by eseidel — APPROVED** [review]
What is the user looking for?  My guess is they care more about the name than the id and we should list that first?

Also we probably want to move to shortened ids in many places eventually (e.g. first N digits)

**Comment by eseidel** [comment]
Anyway, it's good to go as-is, but consider shortening the id to just the first 4-8 chars or moving it to not be the first thing?

**Comment by felangel** [comment]
> What is the user looking for? My guess is they care more about the name than the id and we should list that first?
> 
> Also we probably want to move to shortened ids in many places eventually (e.g. first N digits)

They'll need the ID for most things since that's how we identify the app on the backend but happy to rearrange and put name first.

**Comment by eseidel** [comment]
Again, it's fine as-is.  More expressing an opinion for us to continue to align on dev-exp taste over time.  Thanks.

**Comment by felangel** [comment]
> Again, it's fine as-is. More expressing an opinion for us to continue to align on dev-exp taste over time. Thanks.

Sounds good. Updated to put app name first, thanks! 👍

**Pull request merged**
