### PR TITLE
feat(shorebird_cli): `shorebird patch android` detects release version

### PR DESCRIPTION
**Pull request by felangel**
## Description

- feat(shorebird_cli): `shorebird patch android` detects release version (part of #1098)

## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by bryanoltman — APPROVED** [review]

**Comment by JunioJsv** [comment]
Hello, this change broke a pipeline in my project, I believe it should be considered as breakchange , I was using this flag --release-version on CI.

**Comment by eseidel** [comment]
> Hello, this change broke a pipeline in my project, I believe it should be considered as breakchange , I was using this flag --release-version on CI.

Apologies, yes we should have used the "break:" qualifier instead of the "feat:" qualifier (we, or at least I, have not been very good about using the qualifiers in our semantic commits).  We did mark and announce it as part of a minor version bump/breaking change.

Regardless, how can we help?  Are there things we can do to help unbreak you?

**Comment by JunioJsv** [comment]
Any alternative to point target version for shorebird patch android command? Without having to edit the version in # pubspec.ymal

**Comment by eseidel** [comment]
> Any alternative to point target version for shorebird patch android command? Without having to edit the version in # pubspec.ymal

Filed as https://github.com/shorebirdtech/shorebird/issues/1170 so it doesn't get forgotten.  Please feel free to file other bugs or comment on that one.

**Pull request merged**
