### PR TITLE
chore(shorebird_cli): add windows and mac to CI test matrix

### PR DESCRIPTION
**Pull request by bryanoltman**

### CODE REVIEW

**Comment by eseidel** [comment]
Is this still an active patch?

**Comment by bryanoltman** [comment]
@felangel do we still want to do this? I had forgotten about this PR and I think it might help, but I'm sort of on the fence re: how much value it will provide if we can't combine coverage data between different OS runs

**Comment by eseidel** [comment]
Is this still needed?

**Comment by bryanoltman** [comment]
This has gotten stale and I'm not sure that it would add a ton of value atm. Closing.

**Pull request closed without merging**
