### PR TITLE
feat(shorebird_cli): add `--force` to `shorebird release`

### LINKED ISSUE #448: feat: add a flag (e.g. `--force` to automatically confirm to release or patch a version
**Description**

I have built my own script to ship a new version. In this script I'm using `shorebird release` and `shorebird patch`. However, when running `shorebird release`, I need to confirm the release:

```
🚀 Ready to create a new release!

📱 App: familymissions (prod) (id)
🍧 Flavor: prod
📦 Release Version: 1.0.1+83
🕹️  Platform: android (arm64, arm32, x86_64)

Would you like to continue? (y/N) Yes
✓ Fetching releases (0.2s)
✓ Creating release (0.2s)
✓ Creating artifacts (10.9s)
```

It would be great to have flag which automatically confirms this, like `--force`.

**Current workaround**

My current workaround is to `echo yes |`:

```sh
echo yes | shorebird release ...
```

### PR DESCRIPTION
**Pull request by rkishan516**
## Description

I have added force flag in shorebird release command.
If given, it will not ask for confirmation for release.
As it's mentioned in #448 .

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by nilsreichardt — COMMENTED** [review]
I think this needs a test

**Comment by rkishan516** [comment]
Sure will add

**Review by felangel — APPROVED** [review]
LGTM thanks so much for the contribution!

**Comment by felangel** [comment]
> Sure will add

Don't worry about it I just added a test, thanks for the contribution!

**Pull request merged**
