### PR TITLE
chore(shorebird_cli)!: remove `alpha` suffix from `ios` commands

### PR DESCRIPTION
**Pull request by felangel**
## Description

- chore(shorebird_cli): remove `alpha` suffix from `ios` commands

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [x] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [X] 🗑️ Chore

### CODE REVIEW

**Review by eseidel — COMMENTED** [review]
Do you think it's worth aliasing *-alpha?  Otherwise we will break people's CI scripts I suspect?

**Review by eseidel — APPROVED** [review]
Maybe we just bump the version to 0.25.0 and move on.

**Review by bryanoltman — APPROVED** [review]
We should probably do a docs pass as well

**Comment by felangel** [comment]
> Maybe we just bump the version to 0.25.0 and move on.

Yeah went back and forth on it. Happy to add an alias for backward compat.

**Comment by felangel** [comment]
> We should probably do a docs pass as well

Yup was planning to do that next.

**Comment by felangel** [comment]
> Maybe we just bump the version to 0.25.0 and move on.

That’s what I was leaning toward but happy to adjust and add an alias for backward compat but we’ll break at some point anyway and if we bump the version to 0.25.0 I think it’s fine 🤷‍♂️

**Comment by eseidel** [comment]
Let’s add an alias. Otherwise this has to match the shorebird setup
revision exactly too, or?

**Comment by felangel** [comment]
> Let’s add an alias. Otherwise this has to match the shorebird setup revision exactly too, or?
> […](#)

Setup shorebird always uses the latest stable version of shorebird by default.

**Pull request merged**
