### PR TITLE
feat: add shorebird_code_push_updater

### PR DESCRIPTION
**Pull request by felangel**
## Description

- feat: add shorebird_code_push_updater

## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by eseidel** [comment]
Do you want it in packages even though it's rust?  🤷

**Comment by eseidel** [comment]
Also, this has two copies of the rust code under two different names?

**Comment by felangel** [comment]
> Also, this has two copies of the rust code under two different names?

yup just resolved.

**Comment by eseidel** [comment]
lgtm.

**Comment by felangel** [comment]
> Do you want it in packages even though it's rust? 🤷

Not sure what the conventions are of rust monorepos happy to move it somewhere else.

**Pull request merged**
