### PR TITLE
fix(updater): hash mismatch

### PR DESCRIPTION
**Pull request by felangel**
## Description

- fix(updater): hash mismatch

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by eseidel — APPROVED** [review]
Oops, sorry I missed this!

**Comment by eseidel** [comment]
I can add a test for this next time I'm in this code.

**Comment by felangel** [comment]
> Oops, sorry I missed this!

Not your fault -- we both missed it sorry about that!

**Comment by felangel** [comment]
> I can add a test for this next time I'm in this code.

Sounds good, thanks! 💙

**Pull request merged**
