### PR TITLE
feat: add a new `cutler rebase`

### PR DESCRIPTION
**Pull request by eseidel**
This one does not attempt to do the rebase for you, rather
prints out shell commands you can  use to do the rebase yourself.

It doesn't yet know how to handle updating DEPS for buildroot or
dart changes, but otherwise I think is complete.

Seems like an improvement over our manual steps at least.

### CODE REVIEW

**Comment by felangel** [comment]
> ## [Codecov](https://app.codecov.io/gh/shorebirdtech/shorebird/pull/1303?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=shorebirdtech) Report
> Patch coverage: **`38.46%`** and project coverage change: **`-0.17%`** ⚠️
> 
> > Comparison is base [(`165d140`)](https://app.codecov.io/gh/shorebirdtech/shorebird/commit/165d140603b7d165f39b838df1394cd5ceafefc8?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=shorebirdtech) 98.97% compared to head [(`586ea3d`)](https://app.codecov.io/gh/shorebirdtech/shorebird/pull/1303?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=shorebirdtech) 98.81%.
> 
> Additional details and impacted files
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/shorebirdtech/shorebird/pull/1303?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=shorebirdtech). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=shorebirdtech).

coverage go down 😱

**Comment by eseidel** [comment]
I've been considering moving cutler over to build_engine.  It may make more sense there (and maybe has less stringent coverage requirement. 🤣 )

**Comment by eseidel** [comment]
I have made sacrifice to the gods of coverage. 🐐

**Comment by felangel** [comment]
> I've been considering moving cutler over to build_engine. It may make more sense there (and maybe has less stringent coverage requirement. 🤣 )

Yeah I was thinking the same thing haha

**Review by felangel — APPROVED** [review]

**Pull request merged**
